  spring:
    application:
      name: wallet-activity-feed

    cache:
      type: simple

    datasource:
      url: jdbc:mysql://localhost:3306/walletdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: wallet
      password: wallet

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true

  app:
    kafka:
      enabled: true
      activity-topic: wallet.activity.events

